// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { PuzzleType } from "./tables/PuzzleType.sol";
import { GameStatus } from "./tables/GameStatus.sol";
import { BuyIn } from "./tables/BuyIn.sol";
import { SubmissionWindow } from "./tables/SubmissionWindow.sol";
import { InviteExpiration } from "./tables/InviteExpiration.sol";
import { GameStartTime } from "./tables/GameStartTime.sol";
import { GamePasswordHash } from "./tables/GamePasswordHash.sol";
import { PuzzleMasterEoa } from "./tables/PuzzleMasterEoa.sol";
import { Player1 } from "./tables/Player1.sol";
import { Player2 } from "./tables/Player2.sol";
import { RematchCount } from "./tables/RematchCount.sol";
import { PlaybackWindow } from "./tables/PlaybackWindow.sol";
import { GamePlayerStartTime } from "./tables/GamePlayerStartTime.sol";
import { Submitted } from "./tables/Submitted.sol";
import { Score } from "./tables/Score.sol";
import { Balance } from "./tables/Balance.sol";
import { VoteRematch } from "./tables/VoteRematch.sol";
import { ProtocolFeeRecipient } from "./tables/ProtocolFeeRecipient.sol";
import { ProtocolFeeBasisPoints } from "./tables/ProtocolFeeBasisPoints.sol";
