// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Puzzle } from "./../common.sol";

/**
 * @title IAsyncPuzzleBetSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IAsyncPuzzleBetSystem {
  function v1__newGame2(
    Puzzle puzzleType,
    uint32 submissionWindowSeconds,
    uint32 playbackWindowSeconds,
    uint inviteExpirationTimestamp,
    address puzzleMaster,
    bytes32 passwordHash
  ) external payable returns (bytes32);

  function v1__joinGame2(bytes32 gameId) external payable;

  function v1__joinGame2(bytes32 gameId, string memory password) external payable;

  function v1__startTurn2(bytes32 gameId) external;

  function v1__cancelPendingGame2(bytes32 gameId) external;

  function v1__submitSolution2(bytes32 gameId, uint32 score, bytes memory puzzleMasterSignature) external;

  function v1__claim2(bytes32 gameId) external;

  function v1__voteRematch2(bytes32 gameId) external;
}
